language: python

python:
    - '3.7'

services:
    - docker

addons:
    ssh_known_hosts: ssh.pythonanywhere.com

before_install:
  - sudo apt-get update
  - sudo apt-get install sshpass

install:
    - pip install -r requirements/requirements-dev.txt 

env:
    - PYTHONPATH=/home/travis/build/gcallah/biblio_engine

script:
    - make tests
