language: python

python:
    - '3.7'

services:
    - docker

addons:
    ssh_known_hosts: ssh.pythonanywhere.com

before_install:
  - sudo apt-get update
  - sudo apt-get install sshpass

install:
    - pip install -r requirements/requirements.txt 

env:
    - PYTHONPATH=/home/travis/build/wm1065/biblio_engine

script:
    - make tests

after_success:
    - ./deploy.sh $pa_api
